config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  get '/prototypes/popular' => 'prototypes#popular'
  get '/prototypes/newest' => 'prototypes#newest'
  resources :tags, only: [:index, :show]
  resources :prototypes do
    resources :tags, only: [:destroy]
    resources :comments
    resources :likes,only:[:create,:destroy]
  end
  resources :users, only: [:show, :edit, :update]

  post   '/like/:prototype_id' => 'likes#like',   as: 'like'
  delete '/like/:prototype_id' => 'likes#unlike', as: 'unlike'
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: :show
  def index
    @prototypes = Prototype.all.includes(:tags).page(params[:page]).per(7)
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
    @prototype.tags.build
  end

  def popular
    @prototypes = Prototype.includes(:user).page(params[:page]).per(10).order('likescount DESC')
    respond_to do |format|
      format.html
      format.json
    end
  end

  def newest
    @prototypes = Prototype.includes(:user).page(params[:page]).per(10).order('created_at DESC')
    respond_to do |format|
      format.html
      format.json
    end
  end

  def popular
    @prototypes = Prototype.includes(:user).page(params[:page]).order('likescount DESC')
    respond_to do |format|
      format.html
      format.json
    end
  end

  def newest
    @prototypes = Prototype.includes(:user).page(params[:page]).order('created_at DESC')
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @prototype = Prototype.new(prototype_params)

    if @prototype.save
      set_tags
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to action: :new, alert: 'New prototype was unsuccessfully created'
     end
  end

  def destroy
    protoype = Prototype.find(params[:id])
    protoype.destroy
  end

  def edit
    @prototype = Prototype.find_by(id: params[:id])
    @prototype.captured_images.find_by(id: params[:id])
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
  end

  def update
    prototype = Prototype.find(params[:id])
    if prototype = prototype.update(all_params)
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to action: :edit, alert: 'YNew prototype was unsuccessfully created'
     end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def set_tags
    new_tags = tag_params.to_h
    @tags = new_tags[:tags_attributes].values
      @tags.each do |tag|
        if tag[:tag].present?
          add_tag = Tag.find_or_create_by(tag: "#{tag[:tag]}")
          @prototype.tags << add_tag
        end
      end
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:id, :content, :status],
    )
  end
  def tag_params
    params.require(:prototype).permit(
      tags_attributes: [:tag, :id]
    )
  end
  def all_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:id, :content, :status],
      tags_attributes: [:tag, :id]
    )
  end

    def update_prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:id, :content, :status]
    )
  end

end

app/views/prototypes/_preview.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images, @prototype.captured_images.main[0] do |image|
              #main-preview
                - if @prototype.captured_images.main.present?
                  = image_tag(@prototype.set_main_thumbnail.large, class: 'main-set', style: "margin: 0 auto;")
              = image.file_field :content, required: true, id: "main-thumbnail"
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload#sub_image_uploader
                  = f.fields_for :captured_images, @prototype.captured_images.sub[i] do |image|
                    - subId = ("sub-preview-" + i.to_s)
                    .sub-preview{id: subId}
                      -# = image_tag(image.content) if image
                    = image.file_field :content, id: "sub-thumbnail","data-id": i
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row
        %h4 Tag List
        = f.fields_for :tags, @prototype.tags do |tag|
          .col-md-3
            = tag.text_field :tag, required: "required", type: "text", placeholder: "ex)tag"
      -# .row
      -#   %h4 Tag List
      -#   .col-md-3
      -#     = f.fields_for :tags do |tag|
      -#       = tag.text_field :tag, placeholder: "ex) Web", required: "required", type: "text"
      -#   .col-md-3
      -#     = f.fields_for :tags do |tag|
      -#       = tag.text_field :tag, placeholder: "ex) Rails", type: "text"
      -#   .col-md-3
      -#     = f.fields_for :tags do |tag|
      -#       = tag.text_field :tag, placeholder: "ex) UI/UX", type: "text"
      .row.text-center.proto-btn
        = f.submit "save", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content.removelist
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
          .btn.btn-default.button{:id => "likes_buttons_#{prototype.id}"}
            = render partial: "likes/like",locals: {prototype:prototype}
        .proto-posted
          = prototype.posted_date
      %ul.proto-tag-list.list-inline
        - prototype.tags.each do |tag|
          %li
            %a.btn.btn-default{_pageexpand_: "#{tag[:id]}", href: "/tags/#{tag[:id]}"} #{tag[:tag]}

app/views/prototypes/destroy.html.haml
%p 削除が完了しました
= link_to "一覧に戻る", root_path ,class:"btn btn-default"

app/views/prototypes/edit.html.haml
-# = render "prototypes/preview"
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images, @prototype.captured_images.main[0] do |image|
              #main-preview
                - if @prototype.captured_images.main.present?
                  = image_tag(@prototype.set_main_thumbnail.large, class: 'main-set', style: "margin: 0 auto;")
              = image.file_field :content, required: true, id: "main-thumbnail"
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload#sub_image_uploader
                  = f.fields_for :captured_images, @prototype.captured_images.sub[i] do |image|
                    - subId = ("sub-preview-" + i.to_s)
                    .sub-preview{id: subId}
                      -# = image_tag(image.content) if image
                    = image.file_field :content, id: "sub-thumbnail","data-id": i
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row
        %h4 Tag List
        = f.fields_for :tags, @prototype.tags do |tag|
          .col-md-3
            = tag.text_field :tag, required: "required", type: "text", placeholder: "ex)tag"
      .row.text-center.proto-btn
        = f.submit "save", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/prototypes/popular",id:"popular_button"
        %li.btn-default.btn-popular
          = link_to "Newest", "/prototypes/newest",id:"newest_button"
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes,locals:{likes: @likes}
    .protolists
.paginate
  = paginate @prototypes

/ .text-center
/   %ul.pagination
/     %li.disabled
/       %a{"aria-label": "Previous", href: "#"}
/         %span{"aria-hidden": "true"} «
/     %li.active
/       %a{href: "#"}
/         1
/         %span.sr-only (current)
/     %li
/       %a{href: "#"} 2
/     %li
/       %a{href: "#"} 3
/     %li
/       %a{href: "#"} 4
/     %li
/       %a{href: "#"} 5
/     %li
/       %a{"aria-label": "Next", href: "#"}
/         %span{"aria-hidden": "true"} »

app/views/prototypes/new.html.haml
-# = render "prototypes/preview"
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images, @prototype.captured_images.main[0] do |image|
              #main-preview
                - if @prototype.captured_images.main.present?
                  = image_tag(@prototype.set_main_thumbnail.large, class: 'main-set', style: "margin: 0 auto;")
              = image.file_field :content, required: true, id: "main-thumbnail"
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload#sub_image_uploader
                  = f.fields_for :captured_images, @prototype.captured_images.sub[i] do |image|
                    - subId = ("sub-preview-" + i.to_s)
                    .sub-preview{id: subId}
                      -# = image_tag(image.content) if image
                    = image.file_field :content, id: "sub-thumbnail","data-id": i
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row
        %h4 Tag List
        .col-md-3
          = f.fields_for :tags do |tag|
            = tag.text_field :tag, placeholder: "ex) Web", required: "required", type: "text"
        .col-md-3
          = f.fields_for :tags do |tag|
            = tag.text_field :tag, placeholder: "ex) Rails", type: "text"
        .col-md-3
          = f.fields_for :tags do |tag|
            = tag.text_field :tag, placeholder: "ex) UI/UX", type: "text"
      .row.text-center.proto-btn
        = f.submit "save", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/newest.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/prototypes/popular",id:"popular_button"
        %li.btn-default.btn-popular
          = link_to "Newest", "/prototypes/newest",id:"newest_button"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes,locals:{likes: @likes}
    .protolists

= paginate @prototypes

/ .text-center
/   %ul.pagination
/     %li.disabled
/       %a{"aria-label": "Previous", href: "#"}
/         %span{"aria-hidden": "true"} «
/     %li.active
/       %a{href: "#"}
/         1
/         %span.sr-only (current)
/     %li
/       %a{href: "#"} 2
/     %li
/       %a{href: "#"} 3
/     %li
/       %a{href: "#"} 4
/     %li
/       %a{href: "#"} 5
/     %li
/       %a{"aria-label": "Next", href: "#"}
/         %span{"aria-hidden": "true"} »

app/views/prototypes/popular.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/prototypes/popular",id:"popular_button"
        %li.btn-default.btn-popular
          = link_to "Newest", "/prototypes/newest",id:"newest_button"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes,locals:{likes: @likes}
    .protolists

= paginate @prototypes

/ .text-center
/   %ul.pagination
/     %li.disabled
/       %a{"aria-label": "Previous", href: "#"}
/         %span{"aria-hidden": "true"} «
/     %li.active
/       %a{href: "#"}
/         1
/         %span.sr-only (current)
/     %li
/       %a{href: "#"} 2
/     %li
/       %a{href: "#"} 3
/     %li
/       %a{href: "#"} 4
/     %li
/       %a{href: "#"} 5
/     %li
/       %a{"aria-label": "Next", href: "#"}
/         %span{"aria-hidden": "true"} »

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
    .col-md-4
      %ul.proto-tag-list.list-inline
        - if user_signed_in? && @prototype.user_id == current_user.id
          %li
            %a{href: "/prototypes/#{@prototype.id}/edit", class: "btn btn-default"} Edit
          %li
            =link_to "DELETE","/prototypes/#{@prototype.id}",method: :delete,class:"btn btn-default"
        %li
          .btn.btn-default.button{:id => "likes_buttons_#{@prototype.id}"}
            = render partial: "likes/like",locals: {prototype:@prototype}
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tags.each do |tag|
          %li
          .card-content.white-text
            %p= simple_format("#{tag[:tag]}")
            = link_to '削除', "/prototypes/#{@prototype.id}/tags/#{tag[:id]}", method: :delete
        -# %li
        -#   %a{href: "#", class: "btn btn-default"} iPad
        -# %li
        -#   %a{href: "#", class: "btn btn-default"} wireframe
    .comment_lists
      - @comments.each do |comment|
        .comment_list
          =image_tag(comment.user.avatar,class:"icon")
          %h3.comment_user_name
            =comment.user.name
          %p.comment_text
            =comment.text
          .comment_list--buttons
            -if user_signed_in? && current_user.id == comment.user_id
              = link_to "DELETE","/prototypes/#{comment.prototype_id}/comments/#{comment.id}",method: :delete,class:"btn btn-default"
              = link_to "EDIT","/prototypes/#{comment.prototype_id}/comments/#{comment.id}/edit",class:"btn btn-default"
    .bottom
    -if user_signed_in?
      %input{name:"current_user_id" ,value:"#{current_user.id}",id:"current_user_id",type:"hidden"}
    =form_for [@prototype,@comment] ,class:"comments_form",id:"new_comment" do |f|
      =f.text_field :text,id:"comment_field",class:"text_field", placeholder:"ここにコメントを入力"
      =f.submit "send",id:"comment_button"