config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  get '/prototypes/popular' => 'prototypes#popular'
  get '/prototypes/newest' => 'prototypes#newest'
  resources :tags, only: [:index, :show]
  resources :prototypes do
    resources :tags, only: [:destroy]
    resources :comments
    resources :likes,only:[:create,:destroy]
  end
  resources :users, only: [:show, :edit, :update]

  post   '/like/:prototype_id' => 'likes#like',   as: 'like'
  delete '/like/:prototype_id' => 'likes#unlike', as: 'unlike'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user

  belongs_to :prototype, counter_cache: :likescount

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :set_prototype

  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @prototype.reload
  end

  private
  def set_prototype
    @prototype = Prototype.find(params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype.reload
  end

end

app/views/likes/_like.html.haml
- if user_signed_in?
  - unless prototype.like_user(current_user.id).blank?
    = link_to prototype_like_path(prototype_id: prototype.id ,id: prototype.likes[0].id), method: :delete, remote: true do
      .vertical_like
        %i.material-icons.red-text.red favorite
        %span いいね
        %span.red-text
          = prototype.likescount
  - else
    = link_to prototype_likes_path(prototype.id), method: :post, remote: true do
      .vertical_like
        %i.material-icons.grey-text.text-darken-2.gray favorite_border
        %span いいね
        %span.grey-text.text-darken-2
          = prototype.likescount
- else
  - if prototype.likescount = 0
    .vertical_like
      %i.material-icons.grey-text.text-darken-2.gray favorite_border
      %span.grey-text.text-darken-2
        = prototype.likescount
  - else
    .vertical_like
      %i.material-icons.red-text.red favorite
      %span.red-text
        = prototype.likescount

app/views/likes/_like_links.html.haml
.like-link{id: "like-link-#{prototype.id}"}
  - if user_signed_in?
    - if current_user.likes.find_by(prototype_id: prototype.id)
      = link_to unlike_path(prototype.id), method: :delete, remote: true do
        .btn
          .glyphicon.glyphicon-heart{id: "heart-#{prototype.id}"}
            いいね
            = prototype.likes.count.to_s
    - else
      = link_to like_path(prototype.id), method: :post, remote: true do
        .btn-default.btn
          .glyphicon.glyphicon-heart-empty{id: "heart-#{prototype.id}"}
            いいね
            = prototype.likes.count.to_s

app/views/likes/create.js.haml
$('#likes_buttons_#{@prototype.id}').html("#{j(render partial: 'likes/like', locals: {prototype: @prototype})}");

app/views/likes/destroy.js.haml
$('#likes_buttons_#{@prototype.id}').html("#{j(render partial: 'likes/like', locals: {prototype: @prototype})}");

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", prototype: @prototype  )) %>');
$("<%= @id_heart %>").removeClass('glyphicon-heart-empty');
$("<%= @id_heart %>").addClass('glyphicon-heart');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", prototype: @prototype  )) %>');
$("<%= @id_heart %>").addClass('glyphicon-heart-empty');
$("<%= @id_heart %>").removeClass('glyphicon-heart');